version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    groups:
      gradle-minor-patch:
        update-types:
          - "minor"
          - "patch"
        exclude-patterns:
          - "org.bouncycastle*"
          - "com.hierynomus:sshj"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "ci(deps)"
    groups:
      github-actions:
        patterns:
          - "*"
