// SPDX-FileCopyrightText: 2026 Kim Daniel Geisthardt
// SPDX-License-Identifier: GPL-3.0-or-later
// Locks the plugin classpath shared by all projects; scripts/relock.sh regenerates buildscript-gradle.lockfile.
buildscript { configurations.classpath { resolutionStrategy.activateDependencyLocking() } }
plugins {
    base
    alias(libs.plugins.kotlin.jvm) apply false
    alias(libs.plugins.kotlin.serialization) apply false
    alias(libs.plugins.compose.multiplatform) apply false
    alias(libs.plugins.compose.compiler) apply false
    id("keyrook.runtime-dependency-check") apply false
}

val lintSources = files(
    "build.gradle.kts", "settings.gradle.kts",
    listOf("core", "app", "build-logic").map { dir -> fileTree(dir) { include("*.gradle.kts", "src/**/*.kt") } },
)
// Workflows, scripts and configuration carry the same header as `#` (or `//` for JavaScript) comments.
val hashCommentSources = listOf("*.yml", "*.yaml", "*.sh", "*.py", "*.toml", "*.properties")
val configSources = files(
    listOf(".github", "scripts", "gradle", "core", "app", "build-logic").map { dir ->
        fileTree(dir) {
            include(hashCommentSources.map { "**/$it" } + "**/*.mjs")
            // The Gradle wrapper files are generated by Gradle; generated build output is not source.
            exclude("wrapper/**", "**/build/**", "**/.gradle/**", "**/.kotlin/**")
        }
    },
    // local.properties is machine-specific and never committed.
    fileTree(rootDir) { include(hashCommentSources + "*.mjs"); exclude("local.properties") },
)
// The Gradle wrapper scripts are generated by Gradle under Apache-2.0 and keep their own header.
val wrapperScripts = files("gradlew", "gradlew.bat")
val lint = tasks.register("lint") {
    group = "verification"
    description = "Checks source license headers and whitespace hygiene."
    inputs.files(lintSources, configSources, wrapperScripts)
    val sources: FileCollection = lintSources
    val configs: FileCollection = configSources
    val wrappers: FileCollection = wrapperScripts
    val root = rootDir
    doLast {
        fun checkWhitespace(source: File, lines: List<String>) {
            lines.forEachIndexed { index, line ->
                check('\t' !in line && line == line.trimEnd()) {
                    "Whitespace violation: ${source.relativeTo(root)}:${index + 1}"
                }
            }
        }
        sources.forEach { source ->
            val lines = source.readLines()
            check(lines.size >= 2 && lines[0].startsWith("// SPDX-FileCopyrightText:") &&
                lines[1] == "// SPDX-License-Identifier: GPL-3.0-or-later") {
                "Missing SPDX header: ${source.relativeTo(root)}"
            }
            checkWhitespace(source, lines)
        }
        configs.forEach { source ->
            val lines = source.readLines()
            val comment = if (source.extension == "mjs") "//" else "#"
            // An executable script may start with a shebang line before the header.
            val header = if (lines.firstOrNull()?.startsWith("#!") == true) lines.drop(1) else lines
            check(header.size >= 2 && header[0].startsWith("$comment SPDX-FileCopyrightText:") &&
                header[1] == "$comment SPDX-License-Identifier: GPL-3.0-or-later") {
                "Missing SPDX header: ${source.relativeTo(root)}"
            }
            checkWhitespace(source, lines)
        }
        wrappers.forEach { source ->
            check(source.readLines().take(30).any { it.endsWith("SPDX-License-Identifier: Apache-2.0") }) {
                "Missing SPDX header: ${source.relativeTo(root)}"
            }
        }
    }
}
tasks.named("check") { dependsOn(lint, ":core:check", ":app:check") }
val releaseVersion = providers.fileContents(layout.projectDirectory.file("version.txt")).asText.get().trim()
check(Regex("[0-9]+\\.[0-9]+\\.[0-9]+").matches(releaseVersion)) { "Invalid version.txt" }
allprojects {
    group = "app.keyrook"
    version = releaseVersion
}
