// SPDX-FileCopyrightText: 2026 Kim Daniel Geisthardt
// SPDX-License-Identifier: GPL-3.0-or-later
package app.keyrook.core.crypto

import org.bouncycastle.crypto.InvalidCipherTextException
import org.bouncycastle.crypto.engines.AESEngine
import org.bouncycastle.crypto.generators.Argon2BytesGenerator
import org.bouncycastle.crypto.modes.GCMBlockCipher
import org.bouncycastle.crypto.params.AEADParameters
import org.bouncycastle.crypto.params.Argon2Parameters
import org.bouncycastle.crypto.params.KeyParameter
import java.security.SecureRandom

class AuthenticationException : Exception("Vault authentication failed")
class InvalidVaultException : Exception("Invalid or unsupported vault")
class ResourceApprovalRequired : Exception("KDF resource approval required")

/** Owns independent copies. Input arrays/secrets remain the caller's responsibility. */
class Credentials(password: Secret, keyFile: ByteArray? = null) : AutoCloseable {
    private val password: Secret
    private val keyFile: ByteArray?
    private var closed = false
    init {
        require(keyFile == null || keyFile.size == 32) { "Key file must contain exactly 32 bytes" }
        password.useChars { require(it.isNotEmpty() && it.size <= 1024) { "Invalid password length" } }
        this.password = password.copy()
        this.keyFile = keyFile?.copyOf()
    }
    @Synchronized internal fun hasKeyFile(): Boolean { check(!closed); return keyFile != null }
    @Synchronized internal fun derive(salt: ByteArray, parameters: KdfParameters): ByteArray {
        check(!closed)
        return password.useUtf8 { VaultCrypto.argon2(it, salt, parameters, keyFile) }
    }
    @Synchronized fun copy(): Credentials { check(!closed); return Credentials(password, keyFile) }
    @Synchronized override fun close() { password.close(); keyFile?.fill(0); closed = true }
    override fun toString() = "Credentials([redacted])"
}

data class KdfParameters(val memoryKiB: Int = 65_536, val iterations: Int = 3, val parallelism: Int = 4) {
    fun validate(allowExpensive: Boolean = false) {
        if (memoryKiB !in 65_536..1_048_576 || iterations !in 1..10 || parallelism !in 1..16 ||
            memoryKiB % (4 * parallelism) != 0) throw InvalidVaultException()
        if (!allowExpensive && (memoryKiB > 262_144 || iterations > 5)) throw ResourceApprovalRequired()
    }
}

internal object VaultCrypto {
    private val random = SecureRandom()
    fun randomBytes(size: Int): ByteArray = ByteArray(size).also(random::nextBytes)

    // Resource limits belong to the format boundary. The primitive also supports RFC test vectors.
    fun argon2(password: ByteArray, salt: ByteArray, params: KdfParameters,
               secret: ByteArray? = null, additional: ByteArray? = null): ByteArray {
        val builder = Argon2Parameters.Builder(Argon2Parameters.ARGON2_id)
            .withVersion(Argon2Parameters.ARGON2_VERSION_13)
            .withMemoryAsKB(params.memoryKiB).withIterations(params.iterations)
            .withParallelism(params.parallelism).withSalt(salt)
            .withSecret(secret).withAdditional(additional)
        val parameters = builder.build()
        val result = ByteArray(32)
        try {
            val generator = Argon2BytesGenerator()
            generator.init(parameters)
            generator.generateBytes(password, result)
            return result
        } catch (e: Exception) {
            result.fill(0)
            throw e
        } finally { parameters.clear(); builder.clear() }
    }

    fun aesGcm(encrypt: Boolean, key: ByteArray, nonce: ByteArray, aad: ByteArray, input: ByteArray): ByteArray {
        require(key.size == 32 && nonce.size == 12)
        val keyParameter = KeyParameter(key)
        val cipher = GCMBlockCipher.newInstance(AESEngine.newInstance())
        var output: ByteArray? = null
        try {
            cipher.init(encrypt, AEADParameters(keyParameter, 128, nonce, aad))
            val buffer = ByteArray(cipher.getOutputSize(input.size))
            output = buffer
            val count = cipher.processBytes(input, 0, input.size, buffer, 0)
            val total = count + cipher.doFinal(buffer, count)
            check(total == buffer.size)
            output = null // Ownership transfers only after tag verification.
            return buffer
        } catch (_: InvalidCipherTextException) {
            throw AuthenticationException()
        } finally {
            output?.fill(0)
            keyParameter.key.fill(0)
            cipher.reset()
        }
    }
}

object KeyFiles {
    /** Caller owns the generated bytes and must keep the file separate from vault backups. */
    fun generate(): ByteArray = VaultCrypto.randomBytes(32)
}
